/* ============================================================
   数据区：以后新增分类 / 模板，只需要在这个文件里改这个对象即可。
   ----------------------------------------------------------
   每个分类(category)：
     key      —— 唯一标识（英文/拼音，不要重复）
     name     —— 显示在网站上的分类名称
     image    —— 分类封面图（显示在首页卡片上）
     items    —— 该分类下的模板数组

   每个模板(item)：
     code     —— 编号，例如 "PST-001"（会显示在卡片和放大图上）
     image    —— 模板图片地址。换成你自己的图片 URL 即可。支持多图逻辑：任何一项的 image 都可以写 1 个到无限多个路径（例：["1.jpg", "2.jpg"]）
     color    —— 占位色块的颜色（没有图片时使用），可选
     ratio    —— 比例控制，例如 "16/9"、"1"、"4/3"、"3/4"，不填默认竖版 3/4
   ============================================================ */
const DATA = [
  {
    key:"Sponsored_Card",
    name:"冠名卡（可改冠歌/情侣卡）",
    image:"./Sponsored_Card_Cover.jpg", /* 分类封面大图 */
    items:[
      {code:"冠名卡-187", image:["./Sponsored_Card_Template/187.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-187", image:["./Sponsored_Card_Template/187.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-186", image:["./Sponsored_Card_Template/186.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-186", image:["./Sponsored_Card_Template/186.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-185", image:["./Sponsored_Card_Template/185.3.jpg"], color:"#C8472B"},
      {code:"冠名卡-185", image:["./Sponsored_Card_Template/185.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-184", image:["./Sponsored_Card_Template/184.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-184", image:["./Sponsored_Card_Template/184.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-183", image:["./Sponsored_Card_Template/183.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-183", image:["./Sponsored_Card_Template/183.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-182", image:["./Sponsored_Card_Template/182.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-182", image:["./Sponsored_Card_Template/182.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-181", image:["./Sponsored_Card_Template/181.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-181", image:["./Sponsored_Card_Template/181.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-180", image:["./Sponsored_Card_Template/180.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-180", image:["./Sponsored_Card_Template/180.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-179", image:["./Sponsored_Card_Template/179.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-179", image:["./Sponsored_Card_Template/179.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-178", image:["./Sponsored_Card_Template/178.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-178", image:["./Sponsored_Card_Template/178.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-177", image:["./Sponsored_Card_Template/177.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-177", image:["./Sponsored_Card_Template/177.jpg"], color:"#C8472B"},
      {code:"冠名卡-176", image:["./Sponsored_Card_Template/176.2.jpg"], color:"#C8472B"},
      {code:"冠名卡-176", image:["./Sponsored_Card_Template/176.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-175", image:["./Sponsored_Card_Template/175.1.jpg"], color:"#C8472B"},
      {code:"冠名卡-175", image:["./Sponsored_Card_Template/175.jpg"], color:"#C8472B"},
      {code:"冠名卡-171", image:["./Sponsored_Card_Template/171.jpg"], color:"#C8472B"},
      {code:"冠名卡-170", image:["./Sponsored_Card_Template/170.jpg"], color:"#C8472B"},
      {code:"冠名卡-169", image:["./Sponsored_Card_Template/169.jpg"], color:"#C8472B"},
      {code:"冠名卡-168", image:["./Sponsored_Card_Template/168.jpg"], color:"#C8472B"},
      {code:"冠名卡-167", image:["./Sponsored_Card_Template/167.jpg"], color:"#C8472B"},
      {code:"冠名卡-166", image:["./Sponsored_Card_Template/166.jpg"], color:"#C8472B"},
      {code:"冠名卡-165", image:["./Sponsored_Card_Template/165.jpg"], color:"#C8472B"},
      {code:"冠名卡-164", image:["./Sponsored_Card_Template/164.jpg"], color:"#C8472B"},
      {code:"冠名卡-163", image:["./Sponsored_Card_Template/163.jpg"], color:"#C8472B"},
      {code:"冠名卡-162", image:["./Sponsored_Card_Template/162.jpg"], color:"#C8472B"},
      {code:"冠名卡-161", image:["./Sponsored_Card_Template/161.jpg"], color:"#C8472B"},
      {code:"冠名卡-160", image:["./Sponsored_Card_Template/160.jpg"], color:"#C8472B"},
      {code:"冠名卡-159", image:["./Sponsored_Card_Template/159.jpg"], color:"#C8472B"},
      {code:"冠名卡-158", image:["./Sponsored_Card_Template/158.jpg"], color:"#C8472B"},
      {code:"冠名卡-157", image:["./Sponsored_Card_Template/157.jpg"], color:"#C8472B"},
      {code:"冠名卡-156", image:["./Sponsored_Card_Template/156.jpg"], color:"#C8472B"},
      {code:"冠名卡-155", image:["./Sponsored_Card_Template/155.jpg"], color:"#C8472B"},
      {code:"冠名卡-154", image:["./Sponsored_Card_Template/154.jpg"], color:"#C8472B"},
      {code:"冠名卡-153", image:["./Sponsored_Card_Template/153.jpg"], color:"#C8472B"},
      {code:"冠名卡-152", image:["./Sponsored_Card_Template/152.jpg"], color:"#C8472B"},
      {code:"冠名卡-151", image:["./Sponsored_Card_Template/151.jpg"], color:"#C8472B"},
      {code:"冠名卡-150", image:["./Sponsored_Card_Template/150.jpg"], color:"#C8472B"},
      {code:"冠名卡-149", image:["./Sponsored_Card_Template/149.jpg"], color:"#C8472B"},
      {code:"冠名卡-148", image:["./Sponsored_Card_Template/148.jpg"], color:"#C8472B"},
      {code:"冠名卡-149", image:["./Sponsored_Card_Template/149.jpg"], color:"#C8472B"},
      {code:"冠名卡-148", image:["./Sponsored_Card_Template/148.jpg"], color:"#C8472B"},
      {code:"冠名卡-147", image:["./Sponsored_Card_Template/147.jpg"], color:"#C8472B"},
      {code:"冠名卡-146", image:["./Sponsored_Card_Template/146.jpg"], color:"#C8472B"},
      {code:"冠名卡-145", image:["./Sponsored_Card_Template/145.jpg"], color:"#C8472B"},
      {code:"冠名卡-144", image:["./Sponsored_Card_Template/144.jpg"], color:"#C8472B"},
      {code:"冠名卡-143", image:["./Sponsored_Card_Template/143.jpg"], color:"#C8472B"},
      {code:"冠名卡-142", image:["./Sponsored_Card_Template/142.jpg"], color:"#C8472B"},
      {code:"冠名卡-141", image:["./Sponsored_Card_Template/141.jpg"], color:"#C8472B"},
      {code:"冠名卡-140", image:["./Sponsored_Card_Template/140.jpg"], color:"#C8472B"},
      {code:"冠名卡-139", image:["./Sponsored_Card_Template/139.jpg"], color:"#C8472B"},
      {code:"冠名卡-138", image:["./Sponsored_Card_Template/138.jpg"], color:"#C8472B"},
      {code:"冠名卡-137", image:["./Sponsored_Card_Template/137.jpg"], color:"#C8472B"},
      {code:"冠名卡-136", image:["./Sponsored_Card_Template/136.jpg"], color:"#C8472B"},
      {code:"冠名卡-135", image:["./Sponsored_Card_Template/135.jpg"], color:"#C8472B"},
      {code:"冠名卡-134", image:["./Sponsored_Card_Template/134.jpg"], color:"#C8472B"},
      {code:"冠名卡-133", image:["./Sponsored_Card_Template/133.jpg"], color:"#C8472B"},
      {code:"冠名卡-130", image:["./Sponsored_Card_Template/130.jpg"], color:"#C8472B"},
      {code:"冠名卡-129", image:["./Sponsored_Card_Template/129.jpg"], color:"#C8472B"},
      {code:"冠名卡-128", image:["./Sponsored_Card_Template/128.jpg"], color:"#C8472B"},
      {code:"冠名卡-127", image:["./Sponsored_Card_Template/127.jpg"], color:"#C8472B"},
      {code:"冠名卡-126", image:["./Sponsored_Card_Template/126.jpg"], color:"#C8472B"},
      {code:"冠名卡-125", image:["./Sponsored_Card_Template/125.jpg"], color:"#C8472B"},
      {code:"冠名卡-124", image:["./Sponsored_Card_Template/124.jpg"], color:"#C8472B"},
      {code:"冠名卡-123", image:["./Sponsored_Card_Template/123.jpg"], color:"#C8472B"},
      {code:"冠名卡-122", image:["./Sponsored_Card_Template/122.jpg"], color:"#C8472B"},
      {code:"冠名卡-121", image:["./Sponsored_Card_Template/121.jpg"], color:"#C8472B"},
      {code:"冠名卡-120", image:["./Sponsored_Card_Template/120.jpg"], color:"#C8472B"},
      {code:"冠名卡-119", image:["./Sponsored_Card_Template/119.jpg"], color:"#C8472B"},
      {code:"冠名卡-118", image:["./Sponsored_Card_Template/118.jpg"], color:"#C8472B"},
      {code:"冠名卡-117", image:["./Sponsored_Card_Template/117.jpg"], color:"#C8472B"},
      {code:"冠名卡-116", image:["./Sponsored_Card_Template/116.jpg"], color:"#C8472B"},
      {code:"冠名卡-115", image:["./Sponsored_Card_Template/115.jpg"], color:"#C8472B"},
      {code:"冠名卡-114", image:["./Sponsored_Card_Template/114.jpg"], color:"#C8472B"},
      {code:"冠名卡-113", image:["./Sponsored_Card_Template/113.jpg"], color:"#C8472B"},
      {code:"冠名卡-112", image:["./Sponsored_Card_Template/112.jpg"], color:"#C8472B"},
      {code:"冠名卡-111", image:["./Sponsored_Card_Template/111.jpg"], color:"#C8472B"},
      {code:"冠名卡-110", image:["./Sponsored_Card_Template/110.jpg"], color:"#C8472B"},
      {code:"冠名卡-109", image:["./Sponsored_Card_Template/109.jpg"], color:"#C8472B"},
      {code:"冠名卡-108", image:["./Sponsored_Card_Template/108.jpg"], color:"#C8472B"},
      {code:"冠名卡-107", image:["./Sponsored_Card_Template/107.jpg"], color:"#C8472B"},
      {code:"冠名卡-106", image:["./Sponsored_Card_Template/106.jpg"], color:"#C8472B"},
      {code:"冠名卡-105", image:["./Sponsored_Card_Template/105.jpg"], color:"#C8472B"},
      {code:"冠名卡-104", image:["./Sponsored_Card_Template/104.jpg"], color:"#C8472B"},
      {code:"冠名卡-103", image:["./Sponsored_Card_Template/103.jpg"], color:"#C8472B"},
      {code:"冠名卡-102", image:["./Sponsored_Card_Template/102.jpg"], color:"#C8472B"},
      {code:"冠名卡-101", image:["./Sponsored_Card_Template/101.jpg"], color:"#C8472B"},
      {code:"冠名卡-100", image:["./Sponsored_Card_Template/100.jpg"], color:"#C8472B"},
      {code:"冠名卡-099", image:["./Sponsored_Card_Template/99.jpg"], color:"#C8472B"},
      {code:"冠名卡-098", image:["./Sponsored_Card_Template/98.jpg"], color:"#C8472B"},
      {code:"冠名卡-097", image:["./Sponsored_Card_Template/97.jpg"], color:"#C8472B"},
      {code:"冠名卡-096", image:["./Sponsored_Card_Template/96.jpg"], color:"#C8472B"},
      {code:"冠名卡-095", image:["./Sponsored_Card_Template/95.jpg"], color:"#C8472B"},
      {code:"冠名卡-094", image:["./Sponsored_Card_Template/94.jpg"], color:"#C8472B"},
      {code:"冠名卡-093", image:["./Sponsored_Card_Template/93.jpg"], color:"#C8472B"},
      {code:"冠名卡-092", image:["./Sponsored_Card_Template/92.jpg"], color:"#C8472B"},
      {code:"冠名卡-091", image:["./Sponsored_Card_Template/91.jpg"], color:"#C8472B"},
      {code:"冠名卡-090", image:["./Sponsored_Card_Template/90.jpg"], color:"#C8472B"},
      {code:"冠名卡-089", image:["./Sponsored_Card_Template/89.jpg"], color:"#C8472B"},
      {code:"冠名卡-088", image:["./Sponsored_Card_Template/88.jpg"], color:"#C8472B"},
      {code:"冠名卡-087", image:["./Sponsored_Card_Template/87.jpg"], color:"#C8472B"},
      {code:"冠名卡-086", image:["./Sponsored_Card_Template/86.jpg"], color:"#C8472B"},
      {code:"冠名卡-085", image:["./Sponsored_Card_Template/85.jpg"], color:"#C8472B"},
      {code:"冠名卡-084", image:["./Sponsored_Card_Template/84.jpg"], color:"#C8472B"},
      {code:"冠名卡-083", image:["./Sponsored_Card_Template/83.jpg"], color:"#C8472B"},
      {code:"冠名卡-082", image:["./Sponsored_Card_Template/82.jpg"], color:"#C8472B"},
      {code:"冠名卡-081", image:["./Sponsored_Card_Template/81.jpg"], color:"#C8472B"},
      {code:"冠名卡-080", image:["./Sponsored_Card_Template/80.jpg"], color:"#C8472B"},
      {code:"冠名卡-079", image:["./Sponsored_Card_Template/79.jpg"], color:"#C8472B"},
      {code:"冠名卡-078", image:["./Sponsored_Card_Template/78.jpg"], color:"#C8472B"},
      {code:"冠名卡-077", image:["./Sponsored_Card_Template/77.jpg"], color:"#C8472B"},
      {code:"冠名卡-076", image:["./Sponsored_Card_Template/76.jpg"], color:"#C8472B"},
      {code:"冠名卡-075", image:["./Sponsored_Card_Template/75.jpg"], color:"#C8472B"},
      {code:"冠名卡-074", image:["./Sponsored_Card_Template/74.jpg"], color:"#C8472B"},
      {code:"冠名卡-073", image:["./Sponsored_Card_Template/73.jpg"], color:"#C8472B"},
      {code:"冠名卡-072", image:["./Sponsored_Card_Template/72.jpg"], color:"#C8472B"},
      {code:"冠名卡-071", image:["./Sponsored_Card_Template/71.jpg"], color:"#C8472B"},
      {code:"冠名卡-070", image:["./Sponsored_Card_Template/70.jpg"], color:"#C8472B"},
      {code:"冠名卡-069", image:["./Sponsored_Card_Template/69.jpg"], color:"#C8472B"},
      {code:"冠名卡-068", image:["./Sponsored_Card_Template/68.jpg"], color:"#C8472B"},
      {code:"冠名卡-067", image:["./Sponsored_Card_Template/67.jpg"], color:"#C8472B"},
      {code:"冠名卡-066", image:["./Sponsored_Card_Template/66.jpg"], color:"#C8472B"},
      {code:"冠名卡-065", image:["./Sponsored_Card_Template/65.jpg"], color:"#C8472B"},
      {code:"冠名卡-064", image:["./Sponsored_Card_Template/64.jpg"], color:"#C8472B"},
      {code:"冠名卡-063", image:["./Sponsored_Card_Template/63.jpg"], color:"#C8472B"},
      {code:"冠名卡-062", image:["./Sponsored_Card_Template/62.jpg"], color:"#C8472B"},
      {code:"冠名卡-061", image:["./Sponsored_Card_Template/61.jpg"], color:"#C8472B"},
      {code:"冠名卡-060", image:["./Sponsored_Card_Template/60.jpg"], color:"#C8472B"},
      {code:"冠名卡-059", image:["./Sponsored_Card_Template/59.jpg"], color:"#C8472B"},
      {code:"冠名卡-058", image:["./Sponsored_Card_Template/58.jpg"], color:"#C8472B"},
      {code:"冠名卡-057", image:["./Sponsored_Card_Template/57.jpg"], color:"#C8472B"},
      {code:"冠名卡-056", image:["./Sponsored_Card_Template/56.jpg"], color:"#C8472B"},
      {code:"冠名卡-055", image:["./Sponsored_Card_Template/55.jpg"], color:"#C8472B"},
      {code:"冠名卡-054", image:["./Sponsored_Card_Template/54.jpg"], color:"#C8472B"},
      {code:"冠名卡-053", image:["./Sponsored_Card_Template/53.jpg"], color:"#C8472B"},
      {code:"冠名卡-052", image:["./Sponsored_Card_Template/52.jpg"], color:"#C8472B"},
      {code:"冠名卡-051", image:["./Sponsored_Card_Template/51.jpg"], color:"#C8472B"},
      {code:"冠名卡-050", image:["./Sponsored_Card_Template/50.jpg"], color:"#C8472B"},
      {code:"冠名卡-049", image:["./Sponsored_Card_Template/49.jpg"], color:"#C8472B"},
      {code:"冠名卡-048", image:["./Sponsored_Card_Template/48.jpg"], color:"#C8472B"},
      {code:"冠名卡-047", image:["./Sponsored_Card_Template/47.jpg"], color:"#C8472B"},
      {code:"冠名卡-046", image:["./Sponsored_Card_Template/46.jpg"], color:"#C8472B"},
      {code:"冠名卡-045", image:["./Sponsored_Card_Template/45.jpg"], color:"#C8472B"},
      {code:"冠名卡-044", image:["./Sponsored_Card_Template/44.jpg"], color:"#C8472B"},
      {code:"冠名卡-043", image:["./Sponsored_Card_Template/43.jpg"], color:"#C8472B"},
      {code:"冠名卡-042", image:["./Sponsored_Card_Template/42.jpg"], color:"#C8472B"},
      {code:"冠名卡-041", image:["./Sponsored_Card_Template/41.jpg"], color:"#C8472B"},
      {code:"冠名卡-040", image:["./Sponsored_Card_Template/40.jpg"], color:"#C8472B"},
      {code:"冠名卡-039", image:["./Sponsored_Card_Template/39.jpg"], color:"#C8472B"},
      {code:"冠名卡-038", image:["./Sponsored_Card_Template/38.jpg"], color:"#C8472B"},
      {code:"冠名卡-037", image:["./Sponsored_Card_Template/37.jpg"], color:"#C8472B"},
      {code:"冠名卡-036", image:["./Sponsored_Card_Template/36.jpg"], color:"#C8472B"},
      {code:"冠名卡-035", image:["./Sponsored_Card_Template/35.jpg"], color:"#C8472B"},
      {code:"冠名卡-034", image:["./Sponsored_Card_Template/34.jpg"], color:"#C8472B"},
      {code:"冠名卡-033", image:["./Sponsored_Card_Template/33.jpg"], color:"#C8472B"},
      {code:"冠名卡-032", image:["./Sponsored_Card_Template/32.jpg"], color:"#C8472B"},
      {code:"冠名卡-031", image:["./Sponsored_Card_Template/31.jpg"], color:"#C8472B"},
      {code:"冠名卡-030", image:["./Sponsored_Card_Template/30.jpg"], color:"#C8472B"},
      {code:"冠名卡-029", image:["./Sponsored_Card_Template/29.jpg"], color:"#C8472B"},
      {code:"冠名卡-028", image:["./Sponsored_Card_Template/28.jpg"], color:"#C8472B"},
      {code:"冠名卡-027", image:["./Sponsored_Card_Template/27.jpg"], color:"#C8472B"},
      {code:"冠名卡-026", image:["./Sponsored_Card_Template/26.jpg"], color:"#C8472B"},
      {code:"冠名卡-025", image:["./Sponsored_Card_Template/25.jpg"], color:"#C8472B"},
      {code:"冠名卡-024", image:["./Sponsored_Card_Template/24.jpg"], color:"#C8472B"},
      {code:"冠名卡-023", image:["./Sponsored_Card_Template/23.jpg"], color:"#C8472B"},
      {code:"冠名卡-022", image:["./Sponsored_Card_Template/22.jpg"], color:"#C8472B"},
      {code:"冠名卡-021", image:["./Sponsored_Card_Template/21.jpg"], color:"#C8472B"},
      {code:"冠名卡-020", image:["./Sponsored_Card_Template/20.jpg"], color:"#C8472B"},
      {code:"冠名卡-019", image:["./Sponsored_Card_Template/19.jpg"], color:"#C8472B"},
      {code:"冠名卡-018", image:["./Sponsored_Card_Template/18.jpg"], color:"#C8472B"},
      {code:"冠名卡-017", image:["./Sponsored_Card_Template/17.jpg"], color:"#C8472B"},
      {code:"冠名卡-016", image:["./Sponsored_Card_Template/16.jpg"], color:"#C8472B"},
      {code:"冠名卡-015", image:["./Sponsored_Card_Template/15.jpg"], color:"#C8472B"},
      {code:"冠名卡-014", image:["./Sponsored_Card_Template/14.jpg"], color:"#C8472B"},
      {code:"冠名卡-013", image:["./Sponsored_Card_Template/13.jpg"], color:"#C8472B"},
      {code:"冠名卡-012", image:["./Sponsored_Card_Template/12.jpg"], color:"#C8472B"},
      {code:"冠名卡-011", image:["./Sponsored_Card_Template/11.jpg"], color:"#C8472B"},
      {code:"冠名卡-010", image:["./Sponsored_Card_Template/10.jpg"], color:"#C8472B"},
      {code:"冠名卡-009", image:["./Sponsored_Card_Template/9.jpg"], color:"#C8472B"},
      {code:"冠名卡-008", image:["./Sponsored_Card_Template/8.jpg"], color:"#C8472B"},
      {code:"冠名卡-007", image:["./Sponsored_Card_Template/7.jpg"], color:"#C8472B"},
      {code:"冠名卡-006", image:["./Sponsored_Card_Template/6.jpg"], color:"#C8472B"},
      {code:"冠名卡-005", image:["./Sponsored_Card_Template/5.jpg"], color:"#C8472B"},
      {code:"冠名卡-004", image:["./Sponsored_Card_Template/4.jpg"], color:"#C8472B"},
      {code:"冠名卡-003", image:["./Sponsored_Card_Template/3.jpg"], color:"#C8472B"},
      {code:"冠名卡-002", image:["./Sponsored_Card_Template/2.jpg"], color:"#C8472B"},
      {code:"冠名卡-001", image:["./Sponsored_Card_Template/1.jpg"], color:"#C8472B"}
    ]
  },
  {
    key:"Sister_Card",
    name:"闺蜜卡",
    image:"./敬请期待.jpg",
    items:[
      {code:"GMF-001", image:["./敬请期待.jpg"], color:"#2B3A67", ratio:"16/9"} /* ratio 可以控制特别款海报为 16:9 比例 */
    ]
  },
  {
    key:"Brother_Card",
    name:"兄弟卡",
    image:"./敬请期待.jpg",
    items:[
      {code:"XDK-001", image:["./敬请期待.jpg"], color:"#6E3B5C"}
    ]
  },
  {
    key:"Sponsored_Wall",
    name:"冠名墙",
    image:"./敬请期待.jpg",
    items:[
      {code:"GMW-001", image:["./敬请期待.jpg"], color:"#9C6B30"}
    ]
  },
  {
    key:"Upgrade_Crown",
    name:"升级冠",
    image:"./Upgrade_Crown_Cover.jpg",
    items:[
      {code:"升级冠-024", image:["./Upgrade_Crown_Template/24.jpg"], color:"#26ad80ff"},
      {code:"升级冠-023", image:["./Upgrade_Crown_Template/23.1.jpg"], color:"#26ad80ff"},
      {code:"升级冠-022", image:["./Upgrade_Crown_Template/22.1.jpg"], color:"#26ad80ff"},
      {code:"升级冠-021", image:["./Upgrade_Crown_Template/21.1.jpg"], color:"#26ad80ff"},
      {code:"升级冠-020", image:["./Upgrade_Crown_Template/20.1.jpg"], color:"#26ad80ff"},
      {code:"升级冠-019", image:["./Upgrade_Crown_Template/19.1.jpg"], color:"#26ad80ff"},
      {code:"升级冠-018", image:["./Upgrade_Crown_Template/18.jpg"], color:"#26ad80ff"},
      {code:"升级冠-017", image:["./Upgrade_Crown_Template/17.jpg"], color:"#26ad80ff"},
      {code:"升级冠-016", image:["./Upgrade_Crown_Template/16.jpg"], color:"#26ad80ff"},
      {code:"升级冠-015", image:["./Upgrade_Crown_Template/15.1.jpg"], color:"#26ad80ff"},
      {code:"升级冠-015", image:["./Upgrade_Crown_Template/15.jpg"], color:"#26ad80ff"},
      {code:"升级冠-014", image:["./Upgrade_Crown_Template/14.jpg"], color:"#26ad80ff"},
      {code:"升级冠-013", image:["./Upgrade_Crown_Template/13.1.jpg"], color:"#26ad80ff"},
      {code:"升级冠-012", image:["./Upgrade_Crown_Template/12.1.jpg"], color:"#26ad80ff"},
      {code:"升级冠-011", image:["./Upgrade_Crown_Template/11.jpg"], color:"#26ad80ff"},
      {code:"升级冠-009", image:["./Upgrade_Crown_Template/9.jpg"], color:"#26ad80ff"},
      {code:"升级冠-007", image:["./Upgrade_Crown_Template/7.jpg"], color:"#26ad80ff"},
      {code:"升级冠-006", image:["./Upgrade_Crown_Template/6.jpg"], color:"#26ad80ff"},
      {code:"升级冠-005", image:["./Upgrade_Crown_Template/5.jpg"], color:"#26ad80ff"},
      {code:"升级冠-004", image:["./Upgrade_Crown_Template/4.jpg"], color:"#26ad80ff"},
      {code:"升级冠-003", image:["./Upgrade_Crown_Template/3.jpg"], color:"#26ad80ff"},
      {code:"升级冠-002", image:["./Upgrade_Crown_Template/2.jpg"], color:"#26ad80ff"}
    ]
  },
  {
    key:"Playlist",
    name:"歌单模板",
    image:"./Playlist_Cover.jpg",
    items:[
      {code:"歌单-084", image:["./Playlist_Template/84.jpg"], color:"#1c5dbeff"},
      {code:"歌单-083", image:["./Playlist_Template/83.jpg"], color:"#1c5dbeff"},
      {code:"歌单-082", image:["./Playlist_Template/82.jpg"], color:"#1c5dbeff"},
      {code:"歌单-081", image:["./Playlist_Template/81.jpg"], color:"#1c5dbeff"},
      {code:"歌单-080", image:["./Playlist_Template/80.jpg"], color:"#1c5dbeff"},
      {code:"歌单-079", image:["./Playlist_Template/79.jpg"], color:"#1c5dbeff"},
      {code:"歌单-078", image:["./Playlist_Template/78.jpg"], color:"#1c5dbeff"},
      {code:"歌单-077", image:["./Playlist_Template/77.jpg"], color:"#1c5dbeff"},
      {code:"歌单-076", image:["./Playlist_Template/76.jpg"], color:"#1c5dbeff"},
      {code:"歌单-075", image:["./Playlist_Template/75.jpg"], color:"#1c5dbeff"},
      {code:"歌单-074", image:["./Playlist_Template/74.jpg"], color:"#1c5dbeff"},
      {code:"歌单-073", image:["./Playlist_Template/73.jpg"], color:"#1c5dbeff"},
      {code:"歌单-072", image:["./Playlist_Template/72.jpg"], color:"#1c5dbeff"},
      {code:"歌单-071", image:["./Playlist_Template/71.jpg"], color:"#1c5dbeff"},
      {code:"歌单-070", image:["./Playlist_Template/70.jpg"], color:"#1c5dbeff"},
      {code:"歌单-069", image:["./Playlist_Template/69.jpg"], color:"#1c5dbeff"},
      {code:"歌单-068", image:["./Playlist_Template/68.jpg"], color:"#1c5dbeff"},
      {code:"歌单-067", image:["./Playlist_Template/67.jpg"], color:"#1c5dbeff"},
      {code:"歌单-066", image:["./Playlist_Template/66.jpg"], color:"#1c5dbeff"},
      {code:"歌单-065", image:["./Playlist_Template/65.jpg"], color:"#1c5dbeff"},
      {code:"歌单-064", image:["./Playlist_Template/64.jpg"], color:"#1c5dbeff"},
      {code:"歌单-063", image:["./Playlist_Template/63.jpg"], color:"#1c5dbeff"},
      {code:"歌单-062", image:["./Playlist_Template/62.jpg"], color:"#1c5dbeff"},
      {code:"歌单-061", image:["./Playlist_Template/61.jpg"], color:"#1c5dbeff"},
      {code:"歌单-060", image:["./Playlist_Template/60.jpg"], color:"#1c5dbeff"},
      {code:"歌单-059", image:["./Playlist_Template/59.jpg"], color:"#1c5dbeff"},
      {code:"歌单-058", image:["./Playlist_Template/58.jpg"], color:"#1c5dbeff"},
      {code:"歌单-057", image:["./Playlist_Template/57.jpg"], color:"#1c5dbeff"},
      {code:"歌单-056", image:["./Playlist_Template/56.jpg"], color:"#1c5dbeff"},
      {code:"歌单-055", image:["./Playlist_Template/55.jpg"], color:"#1c5dbeff"},
      {code:"歌单-054", image:["./Playlist_Template/54.jpg"], color:"#1c5dbeff"},
      {code:"歌单-053", image:["./Playlist_Template/53.jpg"], color:"#1c5dbeff"},
      {code:"歌单-052", image:["./Playlist_Template/52.jpg"], color:"#1c5dbeff"},
      {code:"歌单-051", image:["./Playlist_Template/51.jpg"], color:"#1c5dbeff"},
      {code:"歌单-050", image:["./Playlist_Template/50.jpg"], color:"#1c5dbeff"},
      {code:"歌单-049", image:["./Playlist_Template/49.jpg"], color:"#1c5dbeff"},
      {code:"歌单-048", image:["./Playlist_Template/48.jpg"], color:"#1c5dbeff"},
      {code:"歌单-047", image:["./Playlist_Template/47.jpg"], color:"#1c5dbeff"},
      {code:"歌单-046", image:["./Playlist_Template/46.jpg"], color:"#1c5dbeff"},
      {code:"歌单-045", image:["./Playlist_Template/45.jpg"], color:"#1c5dbeff"},
      {code:"歌单-044", image:["./Playlist_Template/44.jpg"], color:"#1c5dbeff"},
      {code:"歌单-043", image:["./Playlist_Template/43.jpg"], color:"#1c5dbeff"},
      {code:"歌单-042", image:["./Playlist_Template/42.jpg"], color:"#1c5dbeff"},
      {code:"歌单-041", image:["./Playlist_Template/41.jpg"], color:"#1c5dbeff"},
      {code:"歌单-040", image:["./Playlist_Template/40.jpg"], color:"#1c5dbeff"},
      {code:"歌单-039", image:["./Playlist_Template/39.jpg"], color:"#1c5dbeff"},
      {code:"歌单-038", image:["./Playlist_Template/38.jpg"], color:"#1c5dbeff"},
      {code:"歌单-037", image:["./Playlist_Template/37.jpg"], color:"#1c5dbeff"},
      {code:"歌单-036", image:["./Playlist_Template/36.jpg"], color:"#1c5dbeff"},
      {code:"歌单-035", image:["./Playlist_Template/35.jpg"], color:"#1c5dbeff"},
      {code:"歌单-034", image:["./Playlist_Template/34.jpg"], color:"#1c5dbeff"},
      {code:"歌单-033", image:["./Playlist_Template/33.jpg"], color:"#1c5dbeff"},
      {code:"歌单-032", image:["./Playlist_Template/32.jpg"], color:"#1c5dbeff"},
      {code:"歌单-031", image:["./Playlist_Template/31.jpg"], color:"#1c5dbeff"},
      {code:"歌单-030", image:["./Playlist_Template/30.jpg"], color:"#1c5dbeff"},
      {code:"歌单-029", image:["./Playlist_Template/29.jpg"], color:"#1c5dbeff"},
      {code:"歌单-028", image:["./Playlist_Template/28.jpg"], color:"#1c5dbeff"},
      {code:"歌单-027", image:["./Playlist_Template/27.jpg"], color:"#1c5dbeff"},
      {code:"歌单-026", image:["./Playlist_Template/26.jpg"], color:"#1c5dbeff"},
      {code:"歌单-025", image:["./Playlist_Template/25.jpg"], color:"#1c5dbeff"},
      {code:"歌单-024", image:["./Playlist_Template/24.jpg"], color:"#1c5dbeff"},
      {code:"歌单-023", image:["./Playlist_Template/23.jpg"], color:"#1c5dbeff"},
      {code:"歌单-022", image:["./Playlist_Template/22.jpg"], color:"#1c5dbeff"},
      {code:"歌单-021", image:["./Playlist_Template/21.jpg"], color:"#1c5dbeff"},
      {code:"歌单-020", image:["./Playlist_Template/20.jpg"], color:"#1c5dbeff"},
      {code:"歌单-019", image:["./Playlist_Template/19.jpg"], color:"#1c5dbeff"},
      {code:"歌单-018", image:["./Playlist_Template/18.1.jpg"], color:"#1c5dbeff"},
      {code:"歌单-017", image:["./Playlist_Template/17.jpg"], color:"#1c5dbeff"},
      {code:"歌单-016", image:["./Playlist_Template/16.jpg"], color:"#1c5dbeff"},
      {code:"歌单-015", image:["./Playlist_Template/15.jpg"], color:"#1c5dbeff"},
      {code:"歌单-014", image:["./Playlist_Template/14.jpg"], color:"#1c5dbeff"},
      {code:"歌单-013", image:["./Playlist_Template/13.jpg"], color:"#1c5dbeff"},
      {code:"歌单-012", image:["./Playlist_Template/12.jpg"], color:"#1c5dbeff"},
      {code:"歌单-011", image:["./Playlist_Template/11.jpg"], color:"#1c5dbeff"},
      {code:"歌单-010", image:["./Playlist_Template/10.jpg"], color:"#1c5dbeff"},
      {code:"歌单-009", image:["./Playlist_Template/9.jpg"], color:"#1c5dbeff"},
      {code:"歌单-008", image:["./Playlist_Template/8.jpg"], color:"#1c5dbeff"},
      {code:"歌单-007", image:["./Playlist_Template/7.jpg"], color:"#1c5dbeff"},
      {code:"歌单-006", image:["./Playlist_Template/6.jpg"], color:"#1c5dbeff"},
      {code:"歌单-005", image:["./Playlist_Template/5.jpg"], color:"#1c5dbeff"},
      {code:"歌单-004", image:["./Playlist_Template/4.jpg"], color:"#1c5dbeff"},
      {code:"歌单-003", image:["./Playlist_Template/3.jpg"], color:"#1c5dbeff"},
      {code:"歌单-002", image:["./Playlist_Template/2.jpg"], color:"#1c5dbeff"},
      {code:"歌单-001", image:["./Playlist_Template/1.jpg"], color:"#1c5dbeff"}
    ]
  },
  {
    key:"Auction",
    name:"拍卖模板",
    image:"./敬请期待.jpg",
    items:[
      {code:"AUC-001", image:["./敬请期待.jpg"], color:"#dbcf20ff"}
    ]
  },
  {
    key:"Benefits",
    name:"福利模板",
    image:"./敬请期待.jpg",
    items:[
      {code:"WEL-001", image:["./敬请期待.jpg"], color:"#2daeceff"}
    ]
  },
  {
    key:"Room_Background",
    name:"厅背景图",
    image:"./敬请期待.jpg",
    items:[
      {code:"RBG-001", image:["./敬请期待.jpg"], color:"#584eb4ff"}
    ]
  },
  {
    key:"Live_Cover",
    name:"直播封面",
    image:"./Live_Cover.jpg",
    items:[
      {code:"直播-058", image:["./Live_Cover_Template/58.jpg"], color:"#0f5c13ff"},
      {code:"直播-057", image:["./Live_Cover_Template/57.jpg"], color:"#0f5c13ff"},
      {code:"直播-056", image:["./Live_Cover_Template/56.jpg"], color:"#0f5c13ff"},
      {code:"直播-055", image:["./Live_Cover_Template/55.jpg"], color:"#0f5c13ff"},
      {code:"直播-054", image:["./Live_Cover_Template/54.jpg"], color:"#0f5c13ff"},
      {code:"直播-053", image:["./Live_Cover_Template/53.jpg"], color:"#0f5c13ff"},
      {code:"直播-052", image:["./Live_Cover_Template/52.jpg"], color:"#0f5c13ff"},
      {code:"直播-051", image:["./Live_Cover_Template/51.jpg"], color:"#0f5c13ff"},
      {code:"直播-050", image:["./Live_Cover_Template/50.jpg"], color:"#0f5c13ff"},
      {code:"直播-049", image:["./Live_Cover_Template/49.jpg"], color:"#0f5c13ff"},
      {code:"直播-048", image:["./Live_Cover_Template/48.jpg"], color:"#0f5c13ff"},
      {code:"直播-047", image:["./Live_Cover_Template/47.jpg"], color:"#0f5c13ff"},
      {code:"直播-046", image:["./Live_Cover_Template/46.jpg"], color:"#0f5c13ff"},
      {code:"直播-044", image:["./Live_Cover_Template/44.jpg"], color:"#0f5c13ff"},
      {code:"直播-043", image:["./Live_Cover_Template/43.jpg"], color:"#0f5c13ff"},
      {code:"直播-042", image:["./Live_Cover_Template/42.jpg"], color:"#0f5c13ff"},
      {code:"直播-041", image:["./Live_Cover_Template/41.jpg"], color:"#0f5c13ff"},
      {code:"直播-040", image:["./Live_Cover_Template/40.jpg"], color:"#0f5c13ff"},
      {code:"直播-039", image:["./Live_Cover_Template/39.jpg"], color:"#0f5c13ff"},
      {code:"直播-038", image:["./Live_Cover_Template/38.jpg"], color:"#0f5c13ff"},
      {code:"直播-037", image:["./Live_Cover_Template/37.jpg"], color:"#0f5c13ff"},
      {code:"直播-036", image:["./Live_Cover_Template/36.jpg"], color:"#0f5c13ff"},
      {code:"直播-035", image:["./Live_Cover_Template/35.jpg"], color:"#0f5c13ff"},
      {code:"直播-034", image:["./Live_Cover_Template/34.jpg"], color:"#0f5c13ff"},
      {code:"直播-033", image:["./Live_Cover_Template/33.jpg"], color:"#0f5c13ff"},
      {code:"直播-032", image:["./Live_Cover_Template/32.jpg"], color:"#0f5c13ff"},
      {code:"直播-031", image:["./Live_Cover_Template/31.jpg"], color:"#0f5c13ff"},
      {code:"直播-030", image:["./Live_Cover_Template/30.jpg"], color:"#0f5c13ff"},
      {code:"直播-029", image:["./Live_Cover_Template/29.jpg"], color:"#0f5c13ff"},
      {code:"直播-028", image:["./Live_Cover_Template/28.jpg"], color:"#0f5c13ff"},
      {code:"直播-027", image:["./Live_Cover_Template/27.jpg"], color:"#0f5c13ff"},
      {code:"直播-026", image:["./Live_Cover_Template/26.jpg"], color:"#0f5c13ff"},
      {code:"直播-025", image:["./Live_Cover_Template/25.jpg"], color:"#0f5c13ff"},
      {code:"直播-024", image:["./Live_Cover_Template/24.jpg"], color:"#0f5c13ff"},
      {code:"直播-023", image:["./Live_Cover_Template/23.jpg"], color:"#0f5c13ff"},
      {code:"直播-022", image:["./Live_Cover_Template/22.jpg"], color:"#0f5c13ff"},
      {code:"直播-021", image:["./Live_Cover_Template/21.jpg"], color:"#0f5c13ff"},
      {code:"直播-020", image:["./Live_Cover_Template/20.jpg"], color:"#0f5c13ff"},
      {code:"直播-019", image:["./Live_Cover_Template/19.jpg"], color:"#0f5c13ff"},
      {code:"直播-018", image:["./Live_Cover_Template/18.jpg"], color:"#0f5c13ff"},
      {code:"直播-017", image:["./Live_Cover_Template/17.jpg"], color:"#0f5c13ff"},
      {code:"直播-016", image:["./Live_Cover_Template/16.jpg"], color:"#0f5c13ff"},
      {code:"直播-015", image:["./Live_Cover_Template/15.jpg"], color:"#0f5c13ff"},
      {code:"直播-014", image:["./Live_Cover_Template/14.jpg"], color:"#0f5c13ff"},
      {code:"直播-013", image:["./Live_Cover_Template/13.jpg"], color:"#0f5c13ff"},
      {code:"直播-012", image:["./Live_Cover_Template/12.jpg"], color:"#0f5c13ff"},
      {code:"直播-011", image:["./Live_Cover_Template/11.jpg"], color:"#0f5c13ff"},
      {code:"直播-010", image:["./Live_Cover_Template/10.jpg"], color:"#0f5c13ff"},
      {code:"直播-009", image:["./Live_Cover_Template/9.jpg"], color:"#0f5c13ff"},
      {code:"直播-008", image:["./Live_Cover_Template/8.jpg"], color:"#0f5c13ff"},
      {code:"直播-007", image:["./Live_Cover_Template/7.jpg"], color:"#0f5c13ff"},
      {code:"直播-006", image:["./Live_Cover_Template/6.jpg"], color:"#0f5c13ff"},
      {code:"直播-005", image:["./Live_Cover_Template/5.jpg"], color:"#0f5c13ff"},
      {code:"直播-004", image:["./Live_Cover_Template/4.jpg"], color:"#0f5c13ff"},
      {code:"直播-003", image:["./Live_Cover_Template/3.jpg"], color:"#0f5c13ff"},
      {code:"直播-002", image:["./Live_Cover_Template/2.jpg"], color:"#0f5c13ff"},
      {code:"直播-001", image:["./Live_Cover_Template/1.jpg"], color:"#0f5c13ff"}
    ]
  },
  {
    key:"Room_Avatar",
    name:"厅头模板",
    image:"./Room_Avatar_Cover.jpg",
    items:[
      {code:"厅头-149", image:["./Room_Avatar_Template/149.jpg"], color:"#eeae9bff"},
      {code:"厅头-148", image:["./Room_Avatar_Template/148.jpg"], color:"#eeae9bff"},
      {code:"厅头-147", image:["./Room_Avatar_Template/147.jpg"], color:"#eeae9bff"},
      {code:"厅头-146", image:["./Room_Avatar_Template/146.jpg"], color:"#eeae9bff"},
      {code:"厅头-145", image:["./Room_Avatar_Template/145.jpg"], color:"#eeae9bff"},
      {code:"厅头-144", image:["./Room_Avatar_Template/144.jpg"], color:"#eeae9bff"},
      {code:"厅头-143", image:["./Room_Avatar_Template/143.jpg"], color:"#eeae9bff"},
      {code:"厅头-142", image:["./Room_Avatar_Template/142.jpg"], color:"#eeae9bff"},
      {code:"厅头-141", image:["./Room_Avatar_Template/141.1.jpg"], color:"#eeae9bff"},
      {code:"厅头-141", image:["./Room_Avatar_Template/141.jpg"], color:"#eeae9bff"},
      {code:"厅头-140", image:["./Room_Avatar_Template/140.jpg"], color:"#eeae9bff"},
      {code:"厅头-139", image:["./Room_Avatar_Template/139.jpg"], color:"#eeae9bff"},
      {code:"厅头-138", image:["./Room_Avatar_Template/138.jpg"], color:"#eeae9bff"},
      {code:"厅头-137", image:["./Room_Avatar_Template/137.jpg"], color:"#eeae9bff"},
      {code:"厅头-136", image:["./Room_Avatar_Template/136.jpg"], color:"#eeae9bff"},
      {code:"厅头-135", image:["./Room_Avatar_Template/135.jpg"], color:"#eeae9bff"},
      {code:"厅头-134", image:["./Room_Avatar_Template/134.jpg"], color:"#eeae9bff"},
      {code:"厅头-133", image:["./Room_Avatar_Template/133.jpg"], color:"#eeae9bff"},
      {code:"厅头-132", image:["./Room_Avatar_Template/132.jpg"], color:"#eeae9bff"},
      {code:"厅头-131", image:["./Room_Avatar_Template/131.jpg"], color:"#eeae9bff"},
      {code:"厅头-130", image:["./Room_Avatar_Template/130.jpg"], color:"#eeae9bff"},
      {code:"厅头-129", image:["./Room_Avatar_Template/129.jpg"], color:"#eeae9bff"},
      {code:"厅头-128", image:["./Room_Avatar_Template/128.jpg"], color:"#eeae9bff"},
      {code:"厅头-125", image:["./Room_Avatar_Template/125.jpg"], color:"#eeae9bff"},
      {code:"厅头-124", image:["./Room_Avatar_Template/124.jpg"], color:"#eeae9bff"},
      {code:"厅头-122", image:["./Room_Avatar_Template/122.jpg"], color:"#eeae9bff"},
      {code:"厅头-121", image:["./Room_Avatar_Template/121.jpg"], color:"#eeae9bff"},
      {code:"厅头-120", image:["./Room_Avatar_Template/120.jpg"], color:"#eeae9bff"},
      {code:"厅头-119", image:["./Room_Avatar_Template/119.jpg"], color:"#eeae9bff"},
      {code:"厅头-118", image:["./Room_Avatar_Template/118.jpg"], color:"#eeae9bff"},
      {code:"厅头-117", image:["./Room_Avatar_Template/117.jpg"], color:"#eeae9bff"},
      {code:"厅头-116", image:["./Room_Avatar_Template/116.jpg"], color:"#eeae9bff"},
      {code:"厅头-115", image:["./Room_Avatar_Template/115.jpg"], color:"#eeae9bff"},
      {code:"厅头-114", image:["./Room_Avatar_Template/114.jpg"], color:"#eeae9bff"},
      {code:"厅头-113", image:["./Room_Avatar_Template/113.jpg"], color:"#eeae9bff"},
      {code:"厅头-112", image:["./Room_Avatar_Template/112.jpg"], color:"#eeae9bff"},
      {code:"厅头-111", image:["./Room_Avatar_Template/111.jpg"], color:"#eeae9bff"},
      {code:"厅头-110", image:["./Room_Avatar_Template/110.jpg"], color:"#eeae9bff"},
      {code:"厅头-109", image:["./Room_Avatar_Template/109.jpg"], color:"#eeae9bff"},
      {code:"厅头-108", image:["./Room_Avatar_Template/108.jpg"], color:"#eeae9bff"},
      {code:"厅头-107", image:["./Room_Avatar_Template/107.jpg"], color:"#eeae9bff"},
      {code:"厅头-106", image:["./Room_Avatar_Template/106.jpg"], color:"#eeae9bff"},
      {code:"厅头-105", image:["./Room_Avatar_Template/105.jpg"], color:"#eeae9bff"},
      {code:"厅头-104", image:["./Room_Avatar_Template/104.jpg"], color:"#eeae9bff"},
      {code:"厅头-103", image:["./Room_Avatar_Template/103.jpg"], color:"#eeae9bff"},
      {code:"厅头-102", image:["./Room_Avatar_Template/102.jpg"], color:"#eeae9bff"},
      {code:"厅头-101", image:["./Room_Avatar_Template/101.jpg"], color:"#eeae9bff"},
      {code:"厅头-100", image:["./Room_Avatar_Template/100.jpg"], color:"#eeae9bff"},
      {code:"厅头-099", image:["./Room_Avatar_Template/99.jpg"], color:"#eeae9bff"},
      {code:"厅头-098", image:["./Room_Avatar_Template/98.jpg"], color:"#eeae9bff"},
      {code:"厅头-097", image:["./Room_Avatar_Template/97.jpg"], color:"#eeae9bff"},
      {code:"厅头-096", image:["./Room_Avatar_Template/96.jpg"], color:"#eeae9bff"},
      {code:"厅头-095", image:["./Room_Avatar_Template/95.jpg"], color:"#eeae9bff"},
      {code:"厅头-094", image:["./Room_Avatar_Template/94.jpg"], color:"#eeae9bff"},
      {code:"厅头-093", image:["./Room_Avatar_Template/93.jpg"], color:"#eeae9bff"},
      {code:"厅头-092", image:["./Room_Avatar_Template/92.jpg"], color:"#eeae9bff"},
      {code:"厅头-091", image:["./Room_Avatar_Template/91.8.jpg"], color:"#eeae9bff"},
      {code:"厅头-091", image:["./Room_Avatar_Template/91.7.jpg"], color:"#eeae9bff"},
      {code:"厅头-091", image:["./Room_Avatar_Template/91.6.jpg"], color:"#eeae9bff"},
      {code:"厅头-091", image:["./Room_Avatar_Template/91.5.jpg"], color:"#eeae9bff"},
      {code:"厅头-091", image:["./Room_Avatar_Template/91.4.jpg"], color:"#eeae9bff"},
      {code:"厅头-091", image:["./Room_Avatar_Template/91.3.jpg"], color:"#eeae9bff"},
      {code:"厅头-091", image:["./Room_Avatar_Template/91.2.jpg"], color:"#eeae9bff"},
      {code:"厅头-091", image:["./Room_Avatar_Template/91.1.jpg"], color:"#eeae9bff"},
      {code:"厅头-091", image:["./Room_Avatar_Template/91.jpg"], color:"#eeae9bff"},
      {code:"厅头-090", image:["./Room_Avatar_Template/90.jpg"], color:"#eeae9bff"},
      {code:"厅头-089", image:["./Room_Avatar_Template/89.jpg"], color:"#eeae9bff"},
      {code:"厅头-088", image:["./Room_Avatar_Template/88.jpg"], color:"#eeae9bff"},
      {code:"厅头-087", image:["./Room_Avatar_Template/87.jpg"], color:"#eeae9bff"},
      {code:"厅头-086", image:["./Room_Avatar_Template/86.jpg"], color:"#eeae9bff"},
      {code:"厅头-085", image:["./Room_Avatar_Template/85.jpg"], color:"#eeae9bff"},
      {code:"厅头-084", image:["./Room_Avatar_Template/84.jpg"], color:"#eeae9bff"},
      {code:"厅头-082", image:["./Room_Avatar_Template/82.jpg"], color:"#eeae9bff"},
      {code:"厅头-081", image:["./Room_Avatar_Template/81.jpg"], color:"#eeae9bff"},
      {code:"厅头-080", image:["./Room_Avatar_Template/80.jpg"], color:"#eeae9bff"},
      {code:"厅头-079", image:["./Room_Avatar_Template/79.jpg"], color:"#eeae9bff"},
      {code:"厅头-078", image:["./Room_Avatar_Template/78.jpg"], color:"#eeae9bff"},
      {code:"厅头-077", image:["./Room_Avatar_Template/77.jpg"], color:"#eeae9bff"},
      {code:"厅头-076", image:["./Room_Avatar_Template/76.jpg"], color:"#eeae9bff"},
      {code:"厅头-075", image:["./Room_Avatar_Template/75.jpg"], color:"#eeae9bff"},
      {code:"厅头-074", image:["./Room_Avatar_Template/74.jpg"], color:"#eeae9bff"},
      {code:"厅头-073", image:["./Room_Avatar_Template/73.jpg"], color:"#eeae9bff"},
      {code:"厅头-072", image:["./Room_Avatar_Template/72.jpg"], color:"#eeae9bff"},
      {code:"厅头-071", image:["./Room_Avatar_Template/71.jpg"], color:"#eeae9bff"},
      {code:"厅头-070", image:["./Room_Avatar_Template/70.jpg"], color:"#eeae9bff"},
      {code:"厅头-069", image:["./Room_Avatar_Template/69.jpg"], color:"#eeae9bff"},
      {code:"厅头-068", image:["./Room_Avatar_Template/68.jpg"], color:"#eeae9bff"},
      {code:"厅头-067", image:["./Room_Avatar_Template/67.jpg"], color:"#eeae9bff"},
      {code:"厅头-066", image:["./Room_Avatar_Template/66.jpg"], color:"#eeae9bff"},
      {code:"厅头-065", image:["./Room_Avatar_Template/65.jpg"], color:"#eeae9bff"},
      {code:"厅头-064", image:["./Room_Avatar_Template/64.1.jpg"], color:"#eeae9bff"},
      {code:"厅头-064", image:["./Room_Avatar_Template/64.2.jpg"], color:"#eeae9bff"},
      {code:"厅头-063", image:["./Room_Avatar_Template/63.jpg"], color:"#eeae9bff"},
      {code:"厅头-062", image:["./Room_Avatar_Template/62.jpg"], color:"#eeae9bff"},
      {code:"厅头-061", image:["./Room_Avatar_Template/61.jpg"], color:"#eeae9bff"},
      {code:"厅头-060", image:["./Room_Avatar_Template/60.jpg"], color:"#eeae9bff"},
      {code:"厅头-059", image:["./Room_Avatar_Template/59.jpg"], color:"#eeae9bff"},
      {code:"厅头-058", image:["./Room_Avatar_Template/58.jpg"], color:"#eeae9bff"},
      {code:"厅头-057", image:["./Room_Avatar_Template/57.jpg"], color:"#eeae9bff"},
      {code:"厅头-056", image:["./Room_Avatar_Template/56.jpg"], color:"#eeae9bff"},
      {code:"厅头-055", image:["./Room_Avatar_Template/55.jpg"], color:"#eeae9bff"},
      {code:"厅头-054", image:["./Room_Avatar_Template/54.jpg"], color:"#eeae9bff"},
      {code:"厅头-053", image:["./Room_Avatar_Template/53.jpg"], color:"#eeae9bff"},
      {code:"厅头-052", image:["./Room_Avatar_Template/52.jpg"], color:"#eeae9bff"},
      {code:"厅头-051", image:["./Room_Avatar_Template/51.jpg"], color:"#eeae9bff"},
      {code:"厅头-050", image:["./Room_Avatar_Template/50.jpg"], color:"#eeae9bff"},
      {code:"厅头-049", image:["./Room_Avatar_Template/49.jpg"], color:"#eeae9bff"},
      {code:"厅头-048", image:["./Room_Avatar_Template/48.jpg"], color:"#eeae9bff"},
      {code:"厅头-047", image:["./Room_Avatar_Template/47.jpg"], color:"#eeae9bff"},
      {code:"厅头-046", image:["./Room_Avatar_Template/46.jpg"], color:"#eeae9bff"},
      {code:"厅头-045", image:["./Room_Avatar_Template/45.jpg"], color:"#eeae9bff"},
      {code:"厅头-044", image:["./Room_Avatar_Template/44.jpg"], color:"#eeae9bff"},
      {code:"厅头-043", image:["./Room_Avatar_Template/43.jpg"], color:"#eeae9bff"},
      {code:"厅头-042", image:["./Room_Avatar_Template/42.jpg"], color:"#eeae9bff"},
      {code:"厅头-041", image:["./Room_Avatar_Template/41.jpg"], color:"#eeae9bff"},
      {code:"厅头-040", image:["./Room_Avatar_Template/40.jpg"], color:"#eeae9bff"},
      {code:"厅头-039", image:["./Room_Avatar_Template/39.jpg"], color:"#eeae9bff"},
      {code:"厅头-038", image:["./Room_Avatar_Template/38.jpg"], color:"#eeae9bff"},
      {code:"厅头-037", image:["./Room_Avatar_Template/37.jpg"], color:"#eeae9bff"},
      {code:"厅头-036", image:["./Room_Avatar_Template/36.jpg"], color:"#eeae9bff"},
      {code:"厅头-035", image:["./Room_Avatar_Template/35.jpg"], color:"#eeae9bff"},
      {code:"厅头-034", image:["./Room_Avatar_Template/34.jpg"], color:"#eeae9bff"},
      {code:"厅头-033", image:["./Room_Avatar_Template/33.jpg"], color:"#eeae9bff"},
      {code:"厅头-032", image:["./Room_Avatar_Template/32.jpg"], color:"#eeae9bff"},
      {code:"厅头-031", image:["./Room_Avatar_Template/31.jpg"], color:"#eeae9bff"},
      {code:"厅头-030", image:["./Room_Avatar_Template/30.jpg"], color:"#eeae9bff"},
      {code:"厅头-029", image:["./Room_Avatar_Template/29.jpg"], color:"#eeae9bff"},
      {code:"厅头-028", image:["./Room_Avatar_Template/28.jpg"], color:"#eeae9bff"},
      {code:"厅头-027", image:["./Room_Avatar_Template/27.jpg"], color:"#eeae9bff"},
      {code:"厅头-026", image:["./Room_Avatar_Template/26.jpg"], color:"#eeae9bff"},
      {code:"厅头-025", image:["./Room_Avatar_Template/25.jpg"], color:"#eeae9bff"},
      {code:"厅头-024", image:["./Room_Avatar_Template/24.jpg"], color:"#eeae9bff"},
      {code:"厅头-023", image:["./Room_Avatar_Template/23.jpg"], color:"#eeae9bff"},
      {code:"厅头-022", image:["./Room_Avatar_Template/22.jpg"], color:"#eeae9bff"},
      {code:"厅头-021", image:["./Room_Avatar_Template/21.jpg"], color:"#eeae9bff"},
      {code:"厅头-020", image:["./Room_Avatar_Template/20.jpg"], color:"#eeae9bff"},
      {code:"厅头-019", image:["./Room_Avatar_Template/19.jpg"], color:"#eeae9bff"},
      {code:"厅头-018", image:["./Room_Avatar_Template/18.jpg"], color:"#eeae9bff"},
      {code:"厅头-017", image:["./Room_Avatar_Template/17.jpg"], color:"#eeae9bff"},
      {code:"厅头-016", image:["./Room_Avatar_Template/16.jpg"], color:"#eeae9bff"},
      {code:"厅头-015", image:["./Room_Avatar_Template/15.jpg"], color:"#eeae9bff"},
      {code:"厅头-014", image:["./Room_Avatar_Template/14.jpg"], color:"#eeae9bff"},
      {code:"厅头-013", image:["./Room_Avatar_Template/13.jpg"], color:"#eeae9bff"},
      {code:"厅头-012", image:["./Room_Avatar_Template/12.jpg"], color:"#eeae9bff"},
      {code:"厅头-011", image:["./Room_Avatar_Template/11.jpg"], color:"#eeae9bff"},
      {code:"厅头-010", image:["./Room_Avatar_Template/10.jpg"], color:"#eeae9bff"},
      {code:"厅头-009", image:["./Room_Avatar_Template/9.jpg"], color:"#eeae9bff"},
      {code:"厅头-008", image:["./Room_Avatar_Template/8.jpg"], color:"#eeae9bff"},
      {code:"厅头-007", image:["./Room_Avatar_Template/7.jpg"], color:"#eeae9bff"},
      {code:"厅头-006", image:["./Room_Avatar_Template/6.jpg"], color:"#eeae9bff"},
      {code:"厅头-005", image:["./Room_Avatar_Template/5.jpg"], color:"#eeae9bff"},
      {code:"厅头-004", image:["./Room_Avatar_Template/4.jpg"], color:"#eeae9bff"},
      {code:"厅头-003", image:["./Room_Avatar_Template/3.jpg"], color:"#eeae9bff"},
      {code:"厅头-002", image:["./Room_Avatar_Template/2.jpg"], color:"#eeae9bff"},
      {code:"厅头-001", image:["./Room_Avatar_Template/1.jpg"], color:"#eeae9bff"}
    ]
  },
  {
    key:"Team_Avatar",
    name:"团头/麦位头像",
    image:"./Team_Avatar_Cover.jpg",
    items:[
      {code:"团麦头-028", image:["./Team_Avatar_Template/28.jpg"], color:"#9dada2ff"},
      {code:"团麦头-027", image:["./Team_Avatar_Template/27.jpg"], color:"#9dada2ff"},
      {code:"团麦头-026", image:["./Team_Avatar_Template/26.jpg"], color:"#9dada2ff"},
      {code:"团麦头-025", image:["./Team_Avatar_Template/25.jpg"], color:"#9dada2ff"},
      {code:"团麦头-024", image:["./Team_Avatar_Template/24.jpg"], color:"#9dada2ff"},
      {code:"团麦头-023", image:["./Team_Avatar_Template/23.jpg"], color:"#9dada2ff"},
      {code:"团麦头-022", image:["./Team_Avatar_Template/22.jpg"], color:"#9dada2ff"},
      {code:"团麦头-021", image:["./Team_Avatar_Template/21.jpg"], color:"#9dada2ff"},
      {code:"团麦头-020", image:["./Team_Avatar_Template/20.jpg"], color:"#9dada2ff"},
      {code:"团麦头-019", image:["./Team_Avatar_Template/19.jpg"], color:"#9dada2ff"},
      {code:"团麦头-018", image:["./Team_Avatar_Template/18.jpg"], color:"#9dada2ff"},
      {code:"团麦头-017", image:["./Team_Avatar_Template/17.jpg"], color:"#9dada2ff"},
      {code:"团麦头-016", image:["./Team_Avatar_Template/16.jpg"], color:"#9dada2ff"},
      {code:"团麦头-015", image:["./Team_Avatar_Template/15.jpg"], color:"#9dada2ff"},
      {code:"团麦头-014", image:["./Team_Avatar_Template/14.jpg"], color:"#9dada2ff"},
      {code:"团麦头-013", image:["./Team_Avatar_Template/13.jpg"], color:"#9dada2ff"},
      {code:"团麦头-012", image:["./Team_Avatar_Template/12.jpg"], color:"#9dada2ff"},
      {code:"团麦头-011", image:["./Team_Avatar_Template/11.jpg"], color:"#9dada2ff"},
      {code:"团麦头-010", image:["./Team_Avatar_Template/10.jpg"], color:"#9dada2ff"},
      {code:"团麦头-009", image:["./Team_Avatar_Template/9.jpg"], color:"#9dada2ff"},
      {code:"团麦头-008", image:["./Team_Avatar_Template/8.jpg"], color:"#9dada2ff"},
      {code:"团麦头-007", image:["./Team_Avatar_Template/7.jpg"], color:"#9dada2ff"},
      {code:"团麦头-006", image:["./Team_Avatar_Template/6.jpg"], color:"#9dada2ff"},
      {code:"团麦头-005", image:["./Team_Avatar_Template/5.jpg"], color:"#9dada2ff"},
      {code:"团麦头-004", image:["./Team_Avatar_Template/4.jpg"], color:"#9dada2ff"},
      {code:"团麦头-003", image:["./Team_Avatar_Template/3.jpg"], color:"#9dada2ff"},
      {code:"团麦头-002", image:["./Team_Avatar_Template/2.jpg"], color:"#9dada2ff"},
      {code:"团麦头-001", image:["./Team_Avatar_Template/1.jpg"], color:"#9dada2ff"}
    ]
  }
];
